/**
 * Token 元数据 - 仅供 CSS 生成脚本使用
 * 这些数据不包含在运行时 bundle 中
 */

/**
 * 基础 Token 分组元数据（用于 CSS 生成）
 */
export const BASE_TOKEN_GROUPS = {
  '色盘 - Cyan': [
    'tokenCyan1',
    'tokenCyan2',
    'tokenCyan3',
    'tokenCyan4',
    'tokenCyan5',
    'tokenCyan6',
    'tokenCyan7',
    'tokenCyan8',
    'tokenCyan9',
    'tokenCyan10',
  ],
  '色盘 - Blue': [
    'tokenBlue1',
    'tokenBlue2',
    'tokenBlue3',
    'tokenBlue4',
    'tokenBlue5',
    'tokenBlue6',
    'tokenBlue7',
    'tokenBlue8',
    'tokenBlue9',
    'tokenBlue10',
  ],
  '色盘 - Purple (P1)': [
    'tokenPurple1',
    'tokenPurple2',
    'tokenPurple3',
    'tokenPurple4',
    'tokenPurple5',
    'tokenPurple6',
    'tokenPurple7',
    'tokenPurple8',
    'tokenPurple9',
    'tokenPurple10',
  ],
  '色盘 - Green': [
    'tokenGreen1',
    'tokenGreen2',
    'tokenGreen3',
    'tokenGreen4',
    'tokenGreen5',
    'tokenGreen6',
    'tokenGreen7',
    'tokenGreen8',
    'tokenGreen9',
    'tokenGreen10',
  ],
  '色盘 - Red': [
    'tokenRed1',
    'tokenRed2',
    'tokenRed3',
    'tokenRed4',
    'tokenRed5',
    'tokenRed6',
    'tokenRed7',
    'tokenRed8',
    'tokenRed9',
    'tokenRed10',
  ],
  '色盘 - Orange': [
    'tokenOrange1',
    'tokenOrange2',
    'tokenOrange3',
    'tokenOrange4',
    'tokenOrange5',
    'tokenOrange6',
    'tokenOrange7',
    'tokenOrange8',
    'tokenOrange9',
    'tokenOrange10',
  ],
  '色盘 - Gold': [
    'tokenGold1',
    'tokenGold2',
    'tokenGold3',
    'tokenGold4',
    'tokenGold5',
    'tokenGold6',
    'tokenGold7',
    'tokenGold8',
    'tokenGold9',
    'tokenGold10',
  ],
  '色盘 - Gray/Neutral (P0)': [
    'tokenGray1',
    'tokenGray2',
    'tokenGray3',
    'tokenGray4',
    'tokenGray5',
    'tokenGray6',
    'tokenGray7',
    'tokenGray8',
    'tokenGray9',
    'tokenGray10',
    'tokenGray11',
    'tokenGray12',
    'tokenGray13',
  ],
  间距Token: [
    'tokenSpacing1',
    'tokenSpacing2',
    'tokenSpacing3',
    'tokenSpacing4',
    'tokenSpacing5',
    'tokenSpacing6',
    'tokenSpacing8',
    'tokenSpacing12',
  ],
  字号Token: [
    'tokenFontSize1',
    'tokenFontSize2',
    'tokenFontSize3',
    'tokenFontSize4',
    'tokenFontSize5',
    'tokenFontSize6',
    'tokenFontSize7',
  ],
  行高Token: ['tokenLineHeight1', 'tokenLineHeight2', 'tokenLineHeight3'],
  圆角Token: [
    'tokenBorderRadius1',
    'tokenBorderRadius2',
    'tokenBorderRadius3',
    'tokenBorderRadius4',
  ],
  控制高度Token: [
    'tokenControlHeight1',
    'tokenControlHeight2',
    'tokenControlHeight3',
    'tokenControlHeight4',
  ],
  '字体族Token (P1)': ['tokenFontFamily', 'tokenFontFamilyCode'],
  '边框Token (P1)': ['tokenLineWidth', 'tokenLineType'],
  '阴影Token (P0)': [
    'tokenShadow1',
    'tokenShadow2',
    'tokenShadow3',
    'tokenShadow4',
  ],
  'z-index层级Token (P0)': [
    'tokenZIndexBase',
    'tokenZIndexPopup',
    'tokenZIndexAffix',
    'tokenZIndexModal',
    'tokenZIndexPopover',
    'tokenZIndexTooltip',
    'tokenZIndexNotification',
  ],
} as const;

/**
 * 从预设色板配置动态生成 CSS 分组元数据
 * @param presetColors 预设色板 Record<name, baseColor>
 * @returns 分组名 → token key 列表
 */
export function generatePresetColorGroups(
  presetColors: Record<string, string>,
): Record<string, string[]> {
  const groups: Record<string, string[]> = {};
  for (const name of Object.keys(presetColors)) {
    const keys: string[] = [];
    for (let i = 1; i <= 10; i++) {
      keys.push(`colorPreset${name}${i}`);
    }
    groups[`预设色板 - ${name}`] = keys;
  }
  return groups;
}

/**
 * 语义 Token 分组元数据（用于 CSS 生成）
 */
export const SEMANTIC_TOKEN_GROUPS = {
  '品牌色 - Primary': [
    'colorPrimary',
    'colorPrimaryHover',
    'colorPrimaryActive',
    'colorPrimaryBg',
    'colorPrimaryBgHover',
    'colorPrimaryBorder',
    'colorPrimaryBorderHover',
    'colorPrimaryText',
    'colorPrimaryTextHover',
    'colorPrimaryTextActive',
  ],
  '功能色 - Success': [
    'colorSuccess',
    'colorSuccessHover',
    'colorSuccessActive',
    'colorSuccessBg',
    'colorSuccessBgHover',
    'colorSuccessBorder',
    'colorSuccessBorderHover',
    'colorSuccessText',
    'colorSuccessTextHover',
    'colorSuccessTextActive',
  ],
  '功能色 - Warning': [
    'colorWarning',
    'colorWarningHover',
    'colorWarningActive',
    'colorWarningBg',
    'colorWarningBgHover',
    'colorWarningBorder',
    'colorWarningBorderHover',
    'colorWarningText',
    'colorWarningTextHover',
    'colorWarningTextActive',
  ],
  '功能色 - Error': [
    'colorError',
    'colorErrorHover',
    'colorErrorActive',
    'colorErrorBg',
    'colorErrorBgHover',
    'colorErrorBorder',
    'colorErrorBorderHover',
    'colorErrorText',
    'colorErrorTextHover',
    'colorErrorTextActive',
    'colorHighlight',
  ],
  '功能色 - Info': [
    'colorInfo',
    'colorInfoHover',
    'colorInfoActive',
    'colorInfoBg',
    'colorInfoBgHover',
    'colorInfoBorder',
    'colorInfoBorderHover',
    'colorInfoText',
    'colorInfoTextHover',
    'colorInfoTextActive',
  ],
  文本色: [
    'colorText',
    'colorTextSecondary',
    'colorTextTertiary',
    'colorTextQuaternary',
    'colorTextDisabled',
    'colorTextPlaceholder',
    'colorTextHeading',
    'colorTextDescription',
    'colorTextBase',
    'colorTextLight',
    'colorWhite',
  ],
  背景色: [
    'colorBgBase',
    'colorBgContainer',
    'colorBgContainerDisabled',
    'colorBgElevated',
    'colorBgLayout',
    'colorBgMask',
    'colorBgSpotlight',
    'colorBgTextHover',
    'colorBgTextActive',
  ],
  填充色: [
    'colorFill',
    'colorFillSecondary',
    'colorFillTertiary',
    'colorFillQuaternary',
    'colorFillContent',
    'colorFillAlter',
  ],
  边框色: [
    'colorBorder',
    'colorBorderSecondary',
    'colorBorderDisabled',
    'colorSplit',
  ],
  控制项颜色: [
    'controlItemBgHover',
    'controlItemBgActive',
    'controlItemBgActiveHover',
  ],
  链接色: ['colorLink', 'colorLinkHover', 'colorLinkActive'],
  图标色: ['colorIcon', 'colorIconHover'],
  '间距 - 语义化命名': [
    'sizeXXS',
    'sizeXS',
    'sizeSM',
    'size',
    'sizeMD',
    'sizeLG',
    'sizeXL',
    'sizeXXL',
    'paddingXXS',
    'paddingXS',
    'paddingSM',
    'padding',
    'paddingMD',
    'paddingLG',
    'paddingXL',
    'paddingXXL',
    'marginXXS',
    'marginXS',
    'marginSM',
    'margin',
    'marginMD',
    'marginLG',
    'marginXL',
    'marginXXL',
  ],
  控制高度: [
    'controlHeightXS',
    'controlHeightSM',
    'controlHeight',
    'controlHeightLG',
  ],
  圆角: ['borderRadiusXS', 'borderRadiusSM', 'borderRadius', 'borderRadiusLG'],
  字号: [
    'fontSizeXS',
    'fontSizeSM',
    'fontSize',
    'fontSizeMD',
    'fontSizeLG',
    'fontSizeXL',
    'fontSizeXXL',
  ],
  行高: ['lineHeightSM', 'lineHeight', 'lineHeightLG'],
  '字体族 (P1)': ['fontFamily', 'fontFamilyCode', 'fontWeightStrong'],
  边框样式: ['borderWidth', 'borderStyle'],
  动效时长: ['motionDurationFast', 'motionDurationMid', 'motionDurationSlow'],
  动效缓动: [
    'motionEaseInOut',
    'motionEaseOut',
    'motionEaseIn',
    'motionEaseOutBack',
    'motionEaseInBack',
    'motionEaseOutCirc',
    'motionEaseInOutCirc',
  ],
  焦点环: ['controlOutline', 'controlOutlineWidth'],
  实心背景色: ['colorBgSolid', 'colorBgSolidHover', 'colorBgSolidActive'],
  '阴影 (P0)': [
    'shadowXS',
    'shadowSM',
    'shadow',
    'shadowMD',
    'shadowLG',
    'shadowXL',
  ],
  'z-index层级 (P0)': [
    'zIndexBase',
    'zIndexPopupBase',
    'zIndexAffix',
    'zIndexModal',
    'zIndexModalMask',
    'zIndexPopover',
    'zIndexDropdown',
    'zIndexTooltip',
    'zIndexNotification',
    'zIndexMessage',
  ],
  '中性色 (P0)': [
    'colorNeutral1',
    'colorNeutral2',
    'colorNeutral3',
    'colorNeutral4',
    'colorNeutral5',
    'colorNeutral6',
    'colorNeutral7',
    'colorNeutral8',
    'colorNeutral9',
    'colorNeutral10',
  ],
} as const;

/**
 * 语义 Token 中使用 var() 引用基础 Token 的映射
 * 亮色模式下这些 Token 使用 var(--tokenXxx) 形式
 */
export const SEMANTIC_VAR_REFS: Record<string, string> = {
  // Primary 使用 Cyan
  colorPrimary: 'tokenCyan6',
  colorPrimaryText: 'tokenCyan6',
  // Success 使用 Green
  colorSuccess: 'tokenGreen6',
  colorSuccessText: 'tokenGreen6',
  // Warning 使用 Gold
  colorWarning: 'tokenGold6',
  colorWarningText: 'tokenGold6',
  // Error 使用 Red
  colorError: 'tokenRed6',
  colorErrorText: 'tokenRed6',
  // Info - 跟随 Primary
  colorInfo: 'colorPrimary',
  colorInfoText: 'colorPrimary',
  // Link - 与 Primary 色系保持一致
  colorLink: 'colorPrimary',
  colorLinkHover: 'colorPrimaryHover',
  colorLinkActive: 'colorPrimaryActive',
  // Size 映射
  sizeXXS: 'tokenSpacing1',
  sizeXS: 'tokenSpacing2',
  sizeSM: 'tokenSpacing3',
  size: 'tokenSpacing4',
  sizeMD: 'tokenSpacing5',
  sizeLG: 'tokenSpacing6',
  sizeXL: 'tokenSpacing8',
  sizeXXL: 'tokenSpacing12',
  // Padding 映射
  paddingXXS: 'tokenSpacing1',
  paddingXS: 'tokenSpacing2',
  paddingSM: 'tokenSpacing3',
  padding: 'tokenSpacing4',
  paddingMD: 'tokenSpacing5',
  paddingLG: 'tokenSpacing6',
  paddingXL: 'tokenSpacing8',
  paddingXXL: 'tokenSpacing12',
  // Margin 映射
  marginXXS: 'tokenSpacing1',
  marginXS: 'tokenSpacing2',
  marginSM: 'tokenSpacing3',
  margin: 'tokenSpacing4',
  marginMD: 'tokenSpacing5',
  marginLG: 'tokenSpacing6',
  marginXL: 'tokenSpacing8',
  marginXXL: 'tokenSpacing12',
  // Control Height 映射
  controlHeightXS: 'tokenControlHeight1',
  controlHeightSM: 'tokenControlHeight2',
  controlHeight: 'tokenControlHeight3',
  controlHeightLG: 'tokenControlHeight4',
  // Border Radius 映射
  borderRadiusXS: 'tokenBorderRadius1',
  borderRadiusSM: 'tokenBorderRadius2',
  borderRadius: 'tokenBorderRadius3',
  borderRadiusLG: 'tokenBorderRadius4',
  // Font Size 映射
  fontSizeXS: 'tokenFontSize1',
  fontSizeSM: 'tokenFontSize2',
  fontSize: 'tokenFontSize3',
  fontSizeMD: 'tokenFontSize4',
  fontSizeLG: 'tokenFontSize5',
  fontSizeXL: 'tokenFontSize6',
  fontSizeXXL: 'tokenFontSize7',
  // Line Height 映射
  lineHeightSM: 'tokenLineHeight1',
  lineHeight: 'tokenLineHeight2',
  lineHeightLG: 'tokenLineHeight3',
  // Font Family 映射
  fontFamily: 'tokenFontFamily',
  fontFamilyCode: 'tokenFontFamilyCode',
  // Border Style 映射
  borderWidth: 'tokenLineWidth',
  borderStyle: 'tokenLineType',
  // Shadow 映射
  shadowXS: 'tokenShadow1',
  shadow: 'tokenShadow2',
  shadowLG: 'tokenShadow3',
  shadowXL: 'tokenShadow4',
  // z-index 映射
  zIndexBase: 'tokenZIndexBase',
  zIndexPopupBase: 'tokenZIndexPopup',
  zIndexAffix: 'tokenZIndexAffix',
  zIndexModal: 'tokenZIndexModal',
  zIndexPopover: 'tokenZIndexPopover',
  zIndexTooltip: 'tokenZIndexTooltip',
  zIndexNotification: 'tokenZIndexNotification',
  // Neutral 映射
  colorNeutral1: 'tokenGray1',
  colorNeutral2: 'tokenGray2',
  colorNeutral3: 'tokenGray3',
  colorNeutral4: 'tokenGray4',
  colorNeutral5: 'tokenGray5',
  colorNeutral6: 'tokenGray6',
  colorNeutral7: 'tokenGray7',
  colorNeutral8: 'tokenGray8',
  colorNeutral9: 'tokenGray9',
  colorNeutral10: 'tokenGray10',
};
