# Phase 1: Issue-triggered AI Sentinel
# Trigger: Add 'sentinel' label to an issue
# Claude Code will analyze the issue and create a fix PR

name: Sentinel - Issue

on:
  issues:
    types: [labeled]

# Prevent concurrent runs for the same issue
concurrency:
  group: sentinel-issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  sentinel:
    if: >-
      github.event.label.name == 'sentinel' &&
      vars.SENTINEL_ENABLED != 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    env:
      BRANCH_NAME: sentinel/issue-${{ github.event.issue.number }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

__PACKAGE_MANAGER_SETUP__

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: __NODE_VERSION__
          cache: __PACKAGE_MANAGER__

      - name: Install dependencies
        run: __INSTALL_CMD__

      - name: Check daily PR limit
        id: pr_limit
        run: |
          TODAY=$(date -u +%Y-%m-%d)
          PR_COUNT=$(gh pr list \
            --label "sentinel" \
            --state all \
            --search "created:>=$TODAY" \
            --json number \
            --jq 'length')

          echo "Today's sentinel PRs: $PR_COUNT"

          if [ "$PR_COUNT" -ge __PR_DAILY_LIMIT__ ]; then
            echo "::warning::Daily PR limit reached (__PR_DAILY_LIMIT__). Skipping."
            echo "limit_reached=true" >> "$GITHUB_OUTPUT"
          else
            echo "limit_reached=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment - fix started
        if: steps.pr_limit.outputs.limit_reached != 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            🤖 **Sentinel Started**

            Claude Code is analyzing this issue and attempting a fix.
            A PR will be created if a fix is found.

            ---
            _Triggered by `sentinel` label_

      - name: Comment - limit reached
        if: steps.pr_limit.outputs.limit_reached == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ **Sentinel Skipped**

            Daily PR limit (__PR_DAILY_LIMIT__) has been reached. Please try again tomorrow or fix manually.

      - name: Create fix branch
        if: steps.pr_limit.outputs.limit_reached != 'true'
        run: git checkout -b "$BRANCH_NAME"

      - name: Run Claude Code
        if: steps.pr_limit.outputs.limit_reached != 'true'
        id: claude
        uses: anthropics/claude-code-action@v1
        env:
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            You are fixing a bug reported in issue #${{ github.event.issue.number }}.

            Issue title: ${{ github.event.issue.title }}
            Issue body:
            ${{ github.event.issue.body }}

            Instructions:
            1. Analyze the issue description carefully
            2. Find the relevant source files
            3. Implement the minimal fix needed
            4. Run type checking to verify: __RUN_CMD__ type-check
            5. Run linting to verify: __RUN_CMD__ lint
            6. Only modify files in these directories: __ALLOWED_PATHS_DISPLAY__
            7. Do NOT modify test files, config files, or package.json
            8. Commit your changes with message: "fix: sentinel for #${{ github.event.issue.number }}"
          claude_args: '--model __MODEL__ --max-turns __MAX_TURNS__ --allowedTools "Edit,Write,Bash,Read,Glob,Grep"'
          settings: |
            {
              "enabledMcpjsonServers": [],
              "hooks": {}
            }

      - name: Validate changed files
        if: steps.pr_limit.outputs.limit_reached != 'true'
        id: validate
        run: |
          CHANGED_FILES=$(git diff origin/__DEFAULT_BRANCH__ HEAD --name-only)

          if [ -z "$CHANGED_FILES" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Validate against whitelist (__ALLOWED_PATHS_DISPLAY__)
          INVALID_FILES=""
          while IFS= read -r file; do
            if [[ ! "$file" =~ __ALLOWED_PATHS_REGEX__ ]]; then
              INVALID_FILES="$INVALID_FILES\n$file"
            fi
          done <<< "$CHANGED_FILES"

          if [ -n "$INVALID_FILES" ]; then
            echo "::error::Files outside allowed directories were modified:$INVALID_FILES"
            echo "invalid_files=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          echo "no_changes=false" >> "$GITHUB_OUTPUT"

      - name: Push branch
        if: >-
          steps.pr_limit.outputs.limit_reached != 'true' &&
          steps.validate.outputs.no_changes != 'true'
        run: git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        id: create_pr
        if: >-
          steps.pr_limit.outputs.limit_reached != 'true' &&
          steps.validate.outputs.no_changes != 'true'
        run: |
          {
            echo "## Sentinel for #${ISSUE_NUMBER}"
            echo ""
            echo "### Issue"
            echo "See issue description for details."
            echo ""
            echo "### Changes"
            echo "This PR was automatically generated by Claude Code to fix the reported issue."
            echo ""
            echo "### Validation"
            echo "- [x] TypeScript type check passed"
            echo "- [x] Lint check passed"
            echo "- [x] Only allowed source directories modified (__ALLOWED_PATHS_DISPLAY__)"
            echo ""
            echo "### Review Checklist"
            echo "- [ ] Changes are correct and minimal"
            echo "- [ ] No unintended side effects"
            echo "- [ ] Tests pass locally"
            echo ""
            echo "---"
            echo "🤖 Generated by AI Sentinel"
          } > /tmp/pr-body.md

          PR_URL=$(gh pr create \
            --head "$BRANCH_NAME" \
            --base "__DEFAULT_BRANCH__" \
            --title "fix: sentinel for #${ISSUE_NUMBER}" \
            --body-file /tmp/pr-body.md \
            --label "sentinel" \
            __REVIEWER_FLAG__)

          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup invalid branch
        if: always() && steps.validate.outputs.invalid_files == 'true'
        run: |
          git push origin --delete "$BRANCH_NAME" 2>/dev/null || true
          echo "::notice::Cleaned up remote branch with invalid changes: $BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment - PR created
        if: steps.create_pr.outputs.pr_url
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Sentinel Complete**

            A fix has been created: ${{ steps.create_pr.outputs.pr_url }}

            Please review the changes before merging.

      - name: Comment - no changes
        if: >-
          steps.pr_limit.outputs.limit_reached != 'true' &&
          steps.validate.outputs.no_changes == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ℹ️ **Sentinel - No Changes**

            Claude Code analyzed the issue but could not determine an automated fix.
            Manual investigation is recommended.

      - name: Comment - failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ❌ **Sentinel Failed**

            The automated fix attempt encountered an error.
            Please check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
