# Phase 4: Scheduled maintenance auto fix
# Runs on a cron schedule to find and fix lint errors, type errors, test failures, and audit issues

name: Sentinel - Scheduled

on:
  schedule:
    # Run every Monday at 03:00 UTC
    - cron: '__CRON_EXPRESSION__'
  workflow_dispatch:
    inputs:
      checks:
        description: 'Comma-separated checks to run (lint,typecheck,test,audit)'
        required: false
        default: '__CHECKS_DEFAULT__'
        type: string

# Prevent concurrent scheduled runs
concurrency:
  group: sentinel-scheduled
  cancel-in-progress: false

jobs:
  maintenance-fix:
    if: vars.SENTINEL_ENABLED != 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    env:
      BRANCH_NAME: sentinel/maintenance-${{ github.run_id }}
      CHECKS: ${{ github.event.inputs.checks || '__CHECKS_DEFAULT__' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

__PACKAGE_MANAGER_SETUP__

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: __NODE_VERSION__
          cache: __PACKAGE_MANAGER__

      - name: Install dependencies
        run: __INSTALL_CMD__

      - name: Run lint check
        id: lint
        if: contains(env.CHECKS, 'lint')
        continue-on-error: true
        run: |
          set +e
          LINT_OUTPUT=$(__LINT_CMD__ 2>&1)
          LINT_EXIT=$?
          set -e

          if [ $LINT_EXIT -ne 0 ]; then
            echo "has_errors=true" >> "$GITHUB_OUTPUT"
            echo "$LINT_OUTPUT" > /tmp/lint-output.txt
          else
            echo "has_errors=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run type check
        id: typecheck
        if: contains(env.CHECKS, 'typecheck')
        continue-on-error: true
        run: |
          set +e
          TC_OUTPUT=$(__TYPECHECK_CMD__ 2>&1)
          TC_EXIT=$?
          set -e

          if [ $TC_EXIT -ne 0 ]; then
            echo "has_errors=true" >> "$GITHUB_OUTPUT"
            echo "$TC_OUTPUT" > /tmp/typecheck-output.txt
          else
            echo "has_errors=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests
        id: test
        if: contains(env.CHECKS, 'test')
        continue-on-error: true
        run: |
          set +e
          TEST_OUTPUT=$(__TEST_CMD__ 2>&1)
          TEST_EXIT=$?
          set -e

          if [ $TEST_EXIT -ne 0 ]; then
            echo "has_errors=true" >> "$GITHUB_OUTPUT"
            echo "$TEST_OUTPUT" > /tmp/test-output.txt
          else
            echo "has_errors=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run security audit
        id: audit
        if: contains(env.CHECKS, 'audit')
        continue-on-error: true
        run: |
          set +e
          AUDIT_OUTPUT=$(__AUDIT_CMD__ 2>&1)
          AUDIT_EXIT=$?
          set -e

          if [ $AUDIT_EXIT -ne 0 ]; then
            echo "has_errors=true" >> "$GITHUB_OUTPUT"
            echo "$AUDIT_OUTPUT" > /tmp/audit-output.txt
          else
            echo "has_errors=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if any issues found
        id: summary
        env:
          LINT_HAS_ERRORS: ${{ steps.lint.outputs.has_errors }}
          TC_HAS_ERRORS: ${{ steps.typecheck.outputs.has_errors }}
          TEST_HAS_ERRORS: ${{ steps.test.outputs.has_errors }}
          AUDIT_HAS_ERRORS: ${{ steps.audit.outputs.has_errors }}
        run: |
          HAS_ISSUES=false
          : > /tmp/maintenance-summary.md

          if [ "$LINT_HAS_ERRORS" == "true" ]; then
            HAS_ISSUES=true
            {
              echo "## Lint Errors"
              echo '```'
              head -100 /tmp/lint-output.txt
              echo '```'
              echo ""
            } >> /tmp/maintenance-summary.md
          fi

          if [ "$TC_HAS_ERRORS" == "true" ]; then
            HAS_ISSUES=true
            {
              echo "## Type Check Errors"
              echo '```'
              head -100 /tmp/typecheck-output.txt
              echo '```'
              echo ""
            } >> /tmp/maintenance-summary.md
          fi

          if [ "$TEST_HAS_ERRORS" == "true" ]; then
            HAS_ISSUES=true
            {
              echo "## Test Failures"
              echo '```'
              head -100 /tmp/test-output.txt
              echo '```'
              echo ""
            } >> /tmp/maintenance-summary.md
          fi

          if [ "$AUDIT_HAS_ERRORS" == "true" ]; then
            HAS_ISSUES=true
            {
              echo "## Audit Issues"
              echo '```'
              head -100 /tmp/audit-output.txt
              echo '```'
              echo ""
            } >> /tmp/maintenance-summary.md
          fi

          if [ "$HAS_ISSUES" == "true" ]; then
            echo "has_issues=true" >> "$GITHUB_OUTPUT"
            # Write to step output for use in subsequent steps
            {
              echo "report_content<<CONTEXT_EOF"
              cat /tmp/maintenance-summary.md
              echo "CONTEXT_EOF"
            } >> "$GITHUB_OUTPUT"
          else
            echo "has_issues=false" >> "$GITHUB_OUTPUT"
            echo "All checks passed! No maintenance needed."
          fi

      - name: Create fix branch
        if: steps.summary.outputs.has_issues == 'true'
        run: git checkout -b "$BRANCH_NAME"

      - name: Run Claude Code
        if: steps.summary.outputs.has_issues == 'true'
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Scheduled maintenance check found the following issues:

            ${{ steps.summary.outputs.report_content }}

            Instructions:
            1. Analyze each category of errors
            2. Fix lint errors first (usually the simplest)
            3. Fix type check errors next
            4. For test failures, fix the SOURCE code, NOT the test files
            5. For audit issues, only fix if the resolution is clear and safe
            6. Run all checks again after fixing: __LINT_CMD__ && __TYPECHECK_CMD__ && __TEST_CMD__
            7. Only modify files in these directories: __ALLOWED_PATHS_DISPLAY__
            8. Do NOT modify test files, config files, or package.json
            9. Commit your changes with message: "fix: scheduled maintenance fixes"
          claude_args: '--model __MODEL__ --max-turns __MAX_TURNS__'

      - name: Validate changed files
        if: steps.summary.outputs.has_issues == 'true'
        id: validate
        run: |
          CHANGED_FILES=$(git diff origin/__DEFAULT_BRANCH__ HEAD --name-only)

          if [ -z "$CHANGED_FILES" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Validate against whitelist (__ALLOWED_PATHS_DISPLAY__)
          INVALID_FILES=""
          while IFS= read -r file; do
            if [[ ! "$file" =~ __ALLOWED_PATHS_REGEX__ ]]; then
              INVALID_FILES="$INVALID_FILES\n$file"
            fi
          done <<< "$CHANGED_FILES"

          if [ -n "$INVALID_FILES" ]; then
            echo "::error::Files outside allowed directories were modified:$INVALID_FILES"
            echo "invalid_files=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          echo "no_changes=false" >> "$GITHUB_OUTPUT"

      - name: Push branch
        if: >-
          steps.summary.outputs.has_issues == 'true' &&
          steps.validate.outputs.no_changes != 'true'
        run: git push origin "$BRANCH_NAME"

      - name: Cleanup invalid branch
        if: always() && steps.validate.outputs.invalid_files == 'true'
        run: |
          git push origin --delete "$BRANCH_NAME" 2>/dev/null || true
          echo "::notice::Cleaned up remote branch with invalid changes: $BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create_pr
        if: >-
          steps.summary.outputs.has_issues == 'true' &&
          steps.validate.outputs.no_changes != 'true'
        run: |
          {
            echo "## Scheduled Maintenance Sentinel"
            echo ""
            echo "### Issues Found and Fixed"
            cat /tmp/maintenance-summary.md
            echo ""
            echo "### Changes"
            echo "This PR was automatically generated by the scheduled maintenance workflow."
            echo ""
            echo "### Review Checklist"
            echo "- [ ] Changes are correct and minimal"
            echo "- [ ] No unintended side effects"
            echo "- [ ] All checks pass"
            echo ""
            echo "---"
            echo "🤖 Generated by AI Sentinel (Scheduled Maintenance)"
          } > /tmp/pr-body.md

          PR_URL=$(gh pr create \
            --head "$BRANCH_NAME" \
            --base "__DEFAULT_BRANCH__" \
            --title "fix: scheduled maintenance fixes" \
            --body-file /tmp/pr-body.md \
            --label "sentinel,maintenance" \
            __REVIEWER_FLAG__)

          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue on failure
        if: >-
          steps.summary.outputs.has_issues == 'true' && failure()
        run: |
          gh issue create \
            --title "🚨 Scheduled maintenance fix failed" \
            --body "## Scheduled Maintenance Failed

          The automated maintenance fix could not be completed.

          ### Action Required
          Please review the quality check results and fix manually.

          ### Workflow Run
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          ---
          🤖 Created by AI Sentinel" \
            --label "bug,sentinel,maintenance"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
