# Phase 2: Post-deploy smoke test failure auto fix
# Triggers after deployment, runs smoke tests, and automatically fixes failures

name: Sentinel - Post Deploy

on:
  deployment_status:
  workflow_run:
    workflows: ['__DEPLOY_WORKFLOW__']
    types: [completed]
  workflow_dispatch:
    inputs:
      deploy_url:
        description: 'Deployed URL to test'
        required: false
        type: string

# Prevent concurrent post-deploy fixes
concurrency:
  group: sentinel-post-deploy
  cancel-in-progress: true

jobs:
  smoke-test-and-fix:
    if: >-
      vars.SENTINEL_ENABLED != 'false' &&
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
      issues: write
      pull-requests: write

    env:
      BRANCH_NAME: sentinel/post-deploy-${{ github.run_id }}
      DEPLOY_URL: ${{ github.event.inputs.deploy_url || github.event.deployment_status.target_url || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: __NODE_VERSION__
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run smoke tests
        id: smoke_tests
        continue-on-error: true
        env:
          BASE_URL: ${{ env.DEPLOY_URL }}
        run: |
          # Run smoke tests and capture output
          set +e
          SMOKE_OUTPUT=$(pnpm test:smoke 2>&1)
          SMOKE_EXIT_CODE=$?
          set -e

          echo "$SMOKE_OUTPUT"

          if [ $SMOKE_EXIT_CODE -ne 0 ]; then
            echo "smoke_failed=true" >> "$GITHUB_OUTPUT"
            # Save failure output for Claude
            echo "$SMOKE_OUTPUT" > /tmp/smoke-test-output.txt
          else
            echo "smoke_failed=false" >> "$GITHUB_OUTPUT"
            echo "All smoke tests passed!"
          fi

      - name: Skip if tests passed
        if: steps.smoke_tests.outputs.smoke_failed != 'true'
        run: echo "Smoke tests passed, no fix needed."

      - name: Prepare context for Claude
        if: steps.smoke_tests.outputs.smoke_failed == 'true'
        id: context
        run: |
          # Collect failure context
          SMOKE_OUTPUT=$(cat /tmp/smoke-test-output.txt)

          # Truncate if too long (keep first 5000 chars)
          if [ ${#SMOKE_OUTPUT} -gt 5000 ]; then
            SMOKE_OUTPUT="${SMOKE_OUTPUT:0:5000}... [truncated]"
          fi

          # Save to file for the prompt
          cat > /tmp/fix-context.md << 'CONTEXT_EOF'
          ## Post-Deploy Smoke Test Failures

          The following smoke tests failed after deployment:

          ```
          CONTEXT_EOF
          echo "$SMOKE_OUTPUT" >> /tmp/fix-context.md
          echo '```' >> /tmp/fix-context.md

          # Write to step output for use in subsequent steps
          {
            echo "prompt_context<<CONTEXT_EOF"
            cat /tmp/fix-context.md
            echo "CONTEXT_EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Run Claude Code
        if: steps.smoke_tests.outputs.smoke_failed == 'true'
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          model: claude-sonnet-4-6
          max_turns: 25
          prompt: |
            Post-deploy smoke tests have failed. Here is the test output:

            ${{ steps.context.outputs.prompt_context }}

            Instructions:
            1. Analyze the smoke test failures carefully
            2. Identify the root cause in the source code
            3. Implement the minimal fix needed
            4. Run type checking: pnpm type-check
            5. Run linting: pnpm lint
            6. Only modify files in src/ or styles/ directories
            7. Do NOT modify test files, config files, or package.json
            8. This is a post-deploy fix, so prioritize correctness and safety
            9. Commit your changes with message: "fix: post-deploy smoke test failure"
          branch: ${{ env.BRANCH_NAME }}
          allowedTools: 'Bash,Read,Write,Edit,Glob,Grep'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Validate changed files
        if: steps.smoke_tests.outputs.smoke_failed == 'true'
        id: validate
        run: |
          # Fetch the sentinel branch from remote (may not exist if Claude made no changes)
          git fetch origin "$BRANCH_NAME" 2>/dev/null || true

          # Check if branch exists on remote
          if ! git rev-parse --verify "origin/$BRANCH_NAME" >/dev/null 2>&1; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Compare remote branches to get changed files (independent of local checkout state)
          CHANGED_FILES=$(git diff "origin/__DEFAULT_BRANCH__...origin/$BRANCH_NAME" --name-only)

          if [ -z "$CHANGED_FILES" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Validate against whitelist
          INVALID_FILES=""
          while IFS= read -r file; do
            if [[ ! "$file" =~ ^src/ ]] && [[ ! "$file" =~ ^styles/ ]]; then
              INVALID_FILES="$INVALID_FILES\n$file"
            fi
          done <<< "$CHANGED_FILES"

          if [ -n "$INVALID_FILES" ]; then
            echo "::error::Files outside allowed directories were modified:$INVALID_FILES"
            echo "invalid_files=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          echo "no_changes=false" >> "$GITHUB_OUTPUT"

      - name: Cleanup invalid branch
        if: always() && steps.validate.outputs.invalid_files == 'true'
        run: |
          git push origin --delete "$BRANCH_NAME" 2>/dev/null || true
          echo "::notice::Cleaned up remote branch with invalid changes: $BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create_pr
        if: >-
          steps.smoke_tests.outputs.smoke_failed == 'true' &&
          steps.validate.outputs.no_changes != 'true'
        run: |
          {
            echo "## Post-Deploy Sentinel"
            echo ""
            echo "### Trigger"
            echo "Smoke tests failed after deployment."
            echo ""
            echo "### Changes"
            echo "This PR was automatically generated by Claude Code to fix post-deploy smoke test failures."
            echo ""
            echo "### Validation"
            echo "- [x] TypeScript type check passed"
            echo "- [x] Lint check passed"
            echo "- [x] Only \`src/\` and \`styles/\` files modified"
            echo ""
            echo "### Review Checklist"
            echo "- [ ] Changes are correct and minimal"
            echo "- [ ] No unintended side effects"
            echo "- [ ] Smoke tests pass with this fix"
            echo "- [ ] No regression in other tests"
            echo ""
            echo "---"
            echo "🤖 Generated by AI Sentinel (Post-Deploy)"
          } > /tmp/pr-body.md

          PR_URL=$(gh pr create \
            --head "$BRANCH_NAME" \
            --base "__DEFAULT_BRANCH__" \
            --title "fix: post-deploy smoke test failure" \
            --body-file /tmp/pr-body.md \
            --label "sentinel,post-deploy,urgent" \
            __REVIEWER_FLAG__)

          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create urgent issue if fix failed
        if: >-
          steps.smoke_tests.outputs.smoke_failed == 'true' &&
          (steps.validate.outputs.no_changes == 'true' ||
          (failure() && steps.validate.outputs.invalid_files != 'true'))
        run: |
          gh issue create \
            --title "🚨 Post-deploy smoke test failure - manual fix needed" \
            --body "## Post-Deploy Failure

          Smoke tests failed after deployment and the automated fix was unable to resolve the issue.

          ### Action Required
          Please investigate and fix manually.

          ### Workflow Run
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          ---
          🤖 Created by AI Sentinel" \
            --label "bug,urgent"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
